import { useTranslation } from './i18n'
const copy = {
  pt: {
    close: 'Fechar', previous: 'Anterior', next: 'Próximo', page: 'Página', of: 'de', found: 'encontrados', available: 'disponíveis', filterDoc: 'Filtrar tipo de documento', filterRegister: 'Filtrar tipo de registro', filterState: 'Filtrar UF', allStates: 'Todas as UFs', emptyHelp: 'Altere a busca ou atualize os cadastros.', waiting: 'Aguardando cadastros', localSearch: 'Selecione um cadastro ou preencha os dados.', rg: 'Número do RG', duplicatePatient: 'Este paciente já está cadastrado nesta empresa.', duplicateRegister: 'Este registro já está cadastrado no sistema.', patientMismatch: 'Os dados digitados diferem do cadastro encontrado para este documento. Confira antes de continuar.', doctorMismatch: 'O nome informado difere do cadastro encontrado para este registro e UF. Confira antes de continuar.', searching: 'Buscando cadastros...', noResults: 'Nenhum resultado encontrado', syncing: 'Sincronizando cadastros', unavailable: 'Base temporariamente indisponível', local: 'Cadastros disponíveis neste dispositivo', fresh: 'Cadastros sincronizados', pending: 'envios pendentes', refreshing: 'atualização em segundo plano', refresh: 'Atualizar cadastros', patients: 'pacientes', doctors: 'médicos', official: 'Consulta Oficial', consultClose: 'Fechar consulta', officialHelp: 'A fonte oficial pode bloquear esta prévia. Abra a janela externa para consultar. Abrir a página não confirma a validade do registro.', external: 'Abrir Janela Externa', type: 'tipo', details: 'Detalhes dos dados', certificateType: 'Tipo de atestado', health: 'Saúde', dental: 'Odontológico', settings: 'Abrir configurações', loading: 'Carregando...',
  },
  en: {
    close: 'Close', previous: 'Previous', next: 'Next', page: 'Page', of: 'of', found: 'found', available: 'available', filterDoc: 'Filter document type', filterRegister: 'Filter registration type', filterState: 'Filter state', allStates: 'All states', emptyHelp: 'Change the search or refresh the directory.', waiting: 'Waiting for directory', localSearch: 'Select a record or fill in the data.', rg: 'RG number', duplicatePatient: 'This patient is already registered with this company.', duplicateRegister: 'This registration is already in the directory.', patientMismatch: 'The entered details differ from the record for this document. Review before continuing.', doctorMismatch: 'The name differs from the record for this registration and state. Review before continuing.', searching: 'Searching records...', noResults: 'No results found', syncing: 'Updating records', unavailable: 'Directory temporarily unavailable', local: 'Records available on this device', fresh: 'Records updated from server', pending: 'pending submissions', refreshing: 'updating in background', refresh: 'Refresh directory', patients: 'patients', doctors: 'doctors', official: 'Official consultation', consultClose: 'Close consultation', officialHelp: 'The official source may block this preview. Open the external window to consult. Opening the page does not confirm registration validity.', external: 'Open external window', type: 'type', details: 'Directory details', certificateType: 'Certificate type', health: 'Health', dental: 'Dental', settings: 'Open settings', loading: 'Loading...',
  },
  es: {
    close: 'Cerrar', previous: 'Anterior', next: 'Siguiente', page: 'Página', of: 'de', found: 'encontrados', available: 'disponibles', filterDoc: 'Filtrar tipo de documento', filterRegister: 'Filtrar tipo de registro', filterState: 'Filtrar estado', allStates: 'Todos los estados', emptyHelp: 'Cambie la búsqueda o actualice los registros.', waiting: 'Esperando registros', localSearch: 'Seleccione un registro o complete los datos.', rg: 'Número de RG', duplicatePatient: 'Este paciente ya está registrado en esta empresa.', duplicateRegister: 'Este registro ya está en el directorio.', patientMismatch: 'Los datos introducidos difieren del registro de este documento. Revise antes de continuar.', doctorMismatch: 'El nombre difiere del registro para esta matrícula y estado. Revise antes de continuar.', searching: 'Buscando registros...', noResults: 'No se encontraron resultados', syncing: 'Actualizando registros', unavailable: 'Directorio temporalmente no disponible', local: 'Registros disponibles en este dispositivo', fresh: 'Registros actualizados del servidor', pending: 'envíos pendientes', refreshing: 'actualizando en segundo plano', refresh: 'Actualizar registros', patients: 'pacientes', doctors: 'médicos', official: 'Consulta oficial', consultClose: 'Cerrar consulta', officialHelp: 'La fuente oficial puede bloquear esta vista. Abra la ventana externa para consultar. Abrir la página no confirma la validez del registro.', external: 'Abrir ventana externa', type: 'tipo', details: 'Detalles de los registros', certificateType: 'Tipo de certificado', health: 'Salud', dental: 'Dental', settings: 'Abrir configuración', loading: 'Cargando...',
  },
}
export function useUiCopy() { const { lang } = useTranslation(); return copy[lang] }
